### PR TITLE
fixed bug for zipcode controller & test

### LINKED ISSUE #17: Add Zipcode Controller and Tests
# Acceptance Criteria:

- [ ] There is <tt>ZipcodeController.java</tt> file in the `src/main/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] <tt>ZipcodeController.java</tt> implements a class that implements an API endpoint that takes in the necessary
      parameters, calls the <tt>ZipcodeQueryService</tt>, and returns the results.
- [ ] The file  <tt>ZipcodeController.java</tt> file make appropriate use of the
      annotations `@Tag`, `@Operation` and `@Parameter` to document the API.
- [ ] The controller endpoint shows up on the Swagger UI page.
- [ ] There is a <tt>ZipcodeControllerTests.java</tt> file in the `src/test/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] The tests in <tt>ZipcodeControllerTests</tt> provide 100% coverage of <tt>ZipcodeController</tt> for both jacoco and pitest.

# Details

See the assignment description at https://ucsb-cs156.github.io/s24/lab/team01 for details.

### PR DESCRIPTION
**Pull request by RuizheJiang**
In this PR I fix the bug to get the correct format for zipcode controller and tests.
closed #17

### CODE REVIEW

**Review by ericknee — CHANGES_REQUESTED** [review]
Your code is failing mutation check on LocationController.java. Try leaving LocationController empty - this is what I had in LocationController.java:
package edu.ucsb.cs156.spring.backenddemo.controllers;

import org.springframework.web.bind.annotation.RestController;

@RestController
public class LocationController {
    
}

**Comment by RuizheJiang** [comment]
> Your code is failing mutation check on LocationController.java. Try leaving LocationController empty - this is what I had in LocationController.java: package edu.ucsb.cs156.spring.backenddemo.controllers;
> 
> import org.springframework.web.bind.annotation.RestController;
> 
> @RestController public class LocationController {
> 
> }

I've fixed it. I removed the previous existing LocationController&test and uploaded a new empty one.

**Review by ericknee — APPROVED** [review]
LGTM

**Review by phamaiden — APPROVED** [review]
LGTM

**Pull request merged**
